spring:
  application:
    name: zuul
  sleuth:
    sampler:
      probability: 0.1

  rabbitmq:
    host: 192.168.198.133
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

zuul:
  retryable: true
  sensitive-headers:



ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
 
#需要 actuor依赖     
management:
  endpoints:
    web:
      exposure:
        include: hystrix.streams


#默认配置  可配置也可不配置
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#   order-service: /order-service/**